# Generated by Django 3.1.7 on 2021-03-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trackingPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lat', models.CharField(max_length=500)),
                ('Lon', models.CharField(max_length=500)),
            ],
        ),
    ]
