# Generated by Django 3.1.7 on 2021-04-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_trackingpoint_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hello', max_length=500)),
                ('ipp', models.CharField(default='NA', max_length=500)),
                ('searchClass', models.CharField(default='NA', max_length=500)),
                ('notes', models.TextField(default='NA')),
            ],
        ),
    ]
