# Generated by Django 3.1.7 on 2021-05-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_projectprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingpoint',
            name='message',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='trackingpoint',
            name='status',
            field=models.CharField(default='Idle', max_length=500),
        ),
    ]
