# Generated by Django 3.1.7 on 2021-05-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auto_20210518_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingpoint',
            name='assignment',
            field=models.TextField(default='NA'),
        ),
    ]
